
// To check if a library is compiled with CocoaPods you
// can use the `COCOAPODS` macro definition which is
// defined in the xcconfigs so it is available in
// headers also when they are imported in the client
// project.


// AFNetworking
#define COCOAPODS_POD_AVAILABLE_AFNetworking
#define COCOAPODS_VERSION_MAJOR_AFNetworking 2
#define COCOAPODS_VERSION_MINOR_AFNetworking 5
#define COCOAPODS_VERSION_PATCH_AFNetworking 3

// AFNetworking/NSURLConnection
#define COCOAPODS_POD_AVAILABLE_AFNetworking_NSURLConnection
#define COCOAPODS_VERSION_MAJOR_AFNetworking_NSURLConnection 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_NSURLConnection 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_NSURLConnection 3

// AFNetworking/NSURLSession
#define COCOAPODS_POD_AVAILABLE_AFNetworking_NSURLSession
#define COCOAPODS_VERSION_MAJOR_AFNetworking_NSURLSession 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_NSURLSession 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_NSURLSession 3

// AFNetworking/Reachability
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Reachability
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Reachability 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Reachability 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_Reachability 3

// AFNetworking/Security
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Security
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Security 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Security 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_Security 3

// AFNetworking/Serialization
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Serialization
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Serialization 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Serialization 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_Serialization 3

// AFNetworking/UIKit
#define COCOAPODS_POD_AVAILABLE_AFNetworking_UIKit
#define COCOAPODS_VERSION_MAJOR_AFNetworking_UIKit 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_UIKit 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_UIKit 3

// Asterism
#define COCOAPODS_POD_AVAILABLE_Asterism
#define COCOAPODS_VERSION_MAJOR_Asterism 1
#define COCOAPODS_VERSION_MINOR_Asterism 0
#define COCOAPODS_VERSION_PATCH_Asterism 0

// CocoaLumberjack
#define COCOAPODS_POD_AVAILABLE_CocoaLumberjack
#define COCOAPODS_VERSION_MAJOR_CocoaLumberjack 1
#define COCOAPODS_VERSION_MINOR_CocoaLumberjack 9
#define COCOAPODS_VERSION_PATCH_CocoaLumberjack 2

// CocoaLumberjack/Core
#define COCOAPODS_POD_AVAILABLE_CocoaLumberjack_Core
#define COCOAPODS_VERSION_MAJOR_CocoaLumberjack_Core 1
#define COCOAPODS_VERSION_MINOR_CocoaLumberjack_Core 9
#define COCOAPODS_VERSION_PATCH_CocoaLumberjack_Core 2

// CocoaLumberjack/Extensions
#define COCOAPODS_POD_AVAILABLE_CocoaLumberjack_Extensions
#define COCOAPODS_VERSION_MAJOR_CocoaLumberjack_Extensions 1
#define COCOAPODS_VERSION_MINOR_CocoaLumberjack_Extensions 9
#define COCOAPODS_VERSION_PATCH_CocoaLumberjack_Extensions 2

// CrashlyticsLumberjack
#define COCOAPODS_POD_AVAILABLE_CrashlyticsLumberjack
#define COCOAPODS_VERSION_MAJOR_CrashlyticsLumberjack 1
#define COCOAPODS_VERSION_MINOR_CrashlyticsLumberjack 0
#define COCOAPODS_VERSION_PATCH_CrashlyticsLumberjack 2

// DateTools
#define COCOAPODS_POD_AVAILABLE_DateTools
#define COCOAPODS_VERSION_MAJOR_DateTools 1
#define COCOAPODS_VERSION_MINOR_DateTools 5
#define COCOAPODS_VERSION_PATCH_DateTools 0

// Ensembles
#define COCOAPODS_POD_AVAILABLE_Ensembles
#define COCOAPODS_VERSION_MAJOR_Ensembles 1
#define COCOAPODS_VERSION_MINOR_Ensembles 3
#define COCOAPODS_VERSION_PATCH_Ensembles 2

// Ensembles/Core
#define COCOAPODS_POD_AVAILABLE_Ensembles_Core
#define COCOAPODS_VERSION_MAJOR_Ensembles_Core 1
#define COCOAPODS_VERSION_MINOR_Ensembles_Core 3
#define COCOAPODS_VERSION_PATCH_Ensembles_Core 2

// FormatterKit
#define COCOAPODS_POD_AVAILABLE_FormatterKit
#define COCOAPODS_VERSION_MAJOR_FormatterKit 1
#define COCOAPODS_VERSION_MINOR_FormatterKit 8
#define COCOAPODS_VERSION_PATCH_FormatterKit 0

// FormatterKit/AddressFormatter
#define COCOAPODS_POD_AVAILABLE_FormatterKit_AddressFormatter
#define COCOAPODS_VERSION_MAJOR_FormatterKit_AddressFormatter 1
#define COCOAPODS_VERSION_MINOR_FormatterKit_AddressFormatter 8
#define COCOAPODS_VERSION_PATCH_FormatterKit_AddressFormatter 0

// FormatterKit/ArrayFormatter
#define COCOAPODS_POD_AVAILABLE_FormatterKit_ArrayFormatter
#define COCOAPODS_VERSION_MAJOR_FormatterKit_ArrayFormatter 1
#define COCOAPODS_VERSION_MINOR_FormatterKit_ArrayFormatter 8
#define COCOAPODS_VERSION_PATCH_FormatterKit_ArrayFormatter 0

// FormatterKit/ColorFormatter
#define COCOAPODS_POD_AVAILABLE_FormatterKit_ColorFormatter
#define COCOAPODS_VERSION_MAJOR_FormatterKit_ColorFormatter 1
#define COCOAPODS_VERSION_MINOR_FormatterKit_ColorFormatter 8
#define COCOAPODS_VERSION_PATCH_FormatterKit_ColorFormatter 0

// FormatterKit/LocationFormatter
#define COCOAPODS_POD_AVAILABLE_FormatterKit_LocationFormatter
#define COCOAPODS_VERSION_MAJOR_FormatterKit_LocationFormatter 1
#define COCOAPODS_VERSION_MINOR_FormatterKit_LocationFormatter 8
#define COCOAPODS_VERSION_PATCH_FormatterKit_LocationFormatter 0

// FormatterKit/NameFormatter
#define COCOAPODS_POD_AVAILABLE_FormatterKit_NameFormatter
#define COCOAPODS_VERSION_MAJOR_FormatterKit_NameFormatter 1
#define COCOAPODS_VERSION_MINOR_FormatterKit_NameFormatter 8
#define COCOAPODS_VERSION_PATCH_FormatterKit_NameFormatter 0

// FormatterKit/OrdinalNumberFormatter
#define COCOAPODS_POD_AVAILABLE_FormatterKit_OrdinalNumberFormatter
#define COCOAPODS_VERSION_MAJOR_FormatterKit_OrdinalNumberFormatter 1
#define COCOAPODS_VERSION_MINOR_FormatterKit_OrdinalNumberFormatter 8
#define COCOAPODS_VERSION_PATCH_FormatterKit_OrdinalNumberFormatter 0

// FormatterKit/TimeIntervalFormatter
#define COCOAPODS_POD_AVAILABLE_FormatterKit_TimeIntervalFormatter
#define COCOAPODS_VERSION_MAJOR_FormatterKit_TimeIntervalFormatter 1
#define COCOAPODS_VERSION_MINOR_FormatterKit_TimeIntervalFormatter 8
#define COCOAPODS_VERSION_PATCH_FormatterKit_TimeIntervalFormatter 0

// FormatterKit/URLRequestFormatter
#define COCOAPODS_POD_AVAILABLE_FormatterKit_URLRequestFormatter
#define COCOAPODS_VERSION_MAJOR_FormatterKit_URLRequestFormatter 1
#define COCOAPODS_VERSION_MINOR_FormatterKit_URLRequestFormatter 8
#define COCOAPODS_VERSION_PATCH_FormatterKit_URLRequestFormatter 0

// FormatterKit/UnitOfInformationFormatter
#define COCOAPODS_POD_AVAILABLE_FormatterKit_UnitOfInformationFormatter
#define COCOAPODS_VERSION_MAJOR_FormatterKit_UnitOfInformationFormatter 1
#define COCOAPODS_VERSION_MINOR_FormatterKit_UnitOfInformationFormatter 8
#define COCOAPODS_VERSION_PATCH_FormatterKit_UnitOfInformationFormatter 0

// MZAppearance
#define COCOAPODS_POD_AVAILABLE_MZAppearance
#define COCOAPODS_VERSION_MAJOR_MZAppearance 1
#define COCOAPODS_VERSION_MINOR_MZAppearance 1
#define COCOAPODS_VERSION_PATCH_MZAppearance 3

// MZFormSheetController
#define COCOAPODS_POD_AVAILABLE_MZFormSheetController
#define COCOAPODS_VERSION_MAJOR_MZFormSheetController 2
#define COCOAPODS_VERSION_MINOR_MZFormSheetController 3
#define COCOAPODS_VERSION_PATCH_MZFormSheetController 6

// MZFormSheetController/Core
#define COCOAPODS_POD_AVAILABLE_MZFormSheetController_Core
#define COCOAPODS_VERSION_MAJOR_MZFormSheetController_Core 2
#define COCOAPODS_VERSION_MINOR_MZFormSheetController_Core 3
#define COCOAPODS_VERSION_PATCH_MZFormSheetController_Core 6

// Mantle
#define COCOAPODS_POD_AVAILABLE_Mantle
#define COCOAPODS_VERSION_MAJOR_Mantle 2
#define COCOAPODS_VERSION_MINOR_Mantle 0
#define COCOAPODS_VERSION_PATCH_Mantle 0

// Mantle/extobjc
#define COCOAPODS_POD_AVAILABLE_Mantle_extobjc
#define COCOAPODS_VERSION_MAJOR_Mantle_extobjc 2
#define COCOAPODS_VERSION_MINOR_Mantle_extobjc 0
#define COCOAPODS_VERSION_PATCH_Mantle_extobjc 0

// Masonry
#define COCOAPODS_POD_AVAILABLE_Masonry
#define COCOAPODS_VERSION_MAJOR_Masonry 0
#define COCOAPODS_VERSION_MINOR_Masonry 6
#define COCOAPODS_VERSION_PATCH_Masonry 1

// OMGHTTPURLRQ
#define COCOAPODS_POD_AVAILABLE_OMGHTTPURLRQ
#define COCOAPODS_VERSION_MAJOR_OMGHTTPURLRQ 2
#define COCOAPODS_VERSION_MINOR_OMGHTTPURLRQ 1
#define COCOAPODS_VERSION_PATCH_OMGHTTPURLRQ 0

// OMGHTTPURLRQ/FormURLEncode
#define COCOAPODS_POD_AVAILABLE_OMGHTTPURLRQ_FormURLEncode
#define COCOAPODS_VERSION_MAJOR_OMGHTTPURLRQ_FormURLEncode 2
#define COCOAPODS_VERSION_MINOR_OMGHTTPURLRQ_FormURLEncode 1
#define COCOAPODS_VERSION_PATCH_OMGHTTPURLRQ_FormURLEncode 0

// OMGHTTPURLRQ/RQ
#define COCOAPODS_POD_AVAILABLE_OMGHTTPURLRQ_RQ
#define COCOAPODS_VERSION_MAJOR_OMGHTTPURLRQ_RQ 2
#define COCOAPODS_VERSION_MINOR_OMGHTTPURLRQ_RQ 1
#define COCOAPODS_VERSION_PATCH_OMGHTTPURLRQ_RQ 0

// OMGHTTPURLRQ/UserAgent
#define COCOAPODS_POD_AVAILABLE_OMGHTTPURLRQ_UserAgent
#define COCOAPODS_VERSION_MAJOR_OMGHTTPURLRQ_UserAgent 2
#define COCOAPODS_VERSION_MINOR_OMGHTTPURLRQ_UserAgent 1
#define COCOAPODS_VERSION_PATCH_OMGHTTPURLRQ_UserAgent 0

// PixateFreestyle
#define COCOAPODS_POD_AVAILABLE_PixateFreestyle
#define COCOAPODS_VERSION_MAJOR_PixateFreestyle 2
#define COCOAPODS_VERSION_MINOR_PixateFreestyle 1
#define COCOAPODS_VERSION_PATCH_PixateFreestyle 4

// PromiseKit
#define COCOAPODS_POD_AVAILABLE_PromiseKit
#define COCOAPODS_VERSION_MAJOR_PromiseKit 1
#define COCOAPODS_VERSION_MINOR_PromiseKit 5
#define COCOAPODS_VERSION_PATCH_PromiseKit 3

// PromiseKit/CALayer
#define COCOAPODS_POD_AVAILABLE_PromiseKit_CALayer
#define COCOAPODS_VERSION_MAJOR_PromiseKit_CALayer 1
#define COCOAPODS_VERSION_MINOR_PromiseKit_CALayer 5
#define COCOAPODS_VERSION_PATCH_PromiseKit_CALayer 3

// PromiseKit/NSNotificationCenter
#define COCOAPODS_POD_AVAILABLE_PromiseKit_NSNotificationCenter
#define COCOAPODS_VERSION_MAJOR_PromiseKit_NSNotificationCenter 1
#define COCOAPODS_VERSION_MINOR_PromiseKit_NSNotificationCenter 5
#define COCOAPODS_VERSION_PATCH_PromiseKit_NSNotificationCenter 3

// PromiseKit/NSURLConnection
#define COCOAPODS_POD_AVAILABLE_PromiseKit_NSURLConnection
#define COCOAPODS_VERSION_MAJOR_PromiseKit_NSURLConnection 1
#define COCOAPODS_VERSION_MINOR_PromiseKit_NSURLConnection 5
#define COCOAPODS_VERSION_PATCH_PromiseKit_NSURLConnection 3

// PromiseKit/Pause
#define COCOAPODS_POD_AVAILABLE_PromiseKit_Pause
#define COCOAPODS_VERSION_MAJOR_PromiseKit_Pause 1
#define COCOAPODS_VERSION_MINOR_PromiseKit_Pause 5
#define COCOAPODS_VERSION_PATCH_PromiseKit_Pause 3

// PromiseKit/Promise
#define COCOAPODS_POD_AVAILABLE_PromiseKit_Promise
#define COCOAPODS_VERSION_MAJOR_PromiseKit_Promise 1
#define COCOAPODS_VERSION_MINOR_PromiseKit_Promise 5
#define COCOAPODS_VERSION_PATCH_PromiseKit_Promise 3

// PromiseKit/UIActionSheet
#define COCOAPODS_POD_AVAILABLE_PromiseKit_UIActionSheet
#define COCOAPODS_VERSION_MAJOR_PromiseKit_UIActionSheet 1
#define COCOAPODS_VERSION_MINOR_PromiseKit_UIActionSheet 5
#define COCOAPODS_VERSION_PATCH_PromiseKit_UIActionSheet 3

// PromiseKit/UIAlertView
#define COCOAPODS_POD_AVAILABLE_PromiseKit_UIAlertView
#define COCOAPODS_VERSION_MAJOR_PromiseKit_UIAlertView 1
#define COCOAPODS_VERSION_MINOR_PromiseKit_UIAlertView 5
#define COCOAPODS_VERSION_PATCH_PromiseKit_UIAlertView 3

// PromiseKit/UIView
#define COCOAPODS_POD_AVAILABLE_PromiseKit_UIView
#define COCOAPODS_VERSION_MAJOR_PromiseKit_UIView 1
#define COCOAPODS_VERSION_MINOR_PromiseKit_UIView 5
#define COCOAPODS_VERSION_PATCH_PromiseKit_UIView 3

// PromiseKit/UIViewController
#define COCOAPODS_POD_AVAILABLE_PromiseKit_UIViewController
#define COCOAPODS_VERSION_MAJOR_PromiseKit_UIViewController 1
#define COCOAPODS_VERSION_MINOR_PromiseKit_UIViewController 5
#define COCOAPODS_VERSION_PATCH_PromiseKit_UIViewController 3

// PromiseKit/Until
#define COCOAPODS_POD_AVAILABLE_PromiseKit_Until
#define COCOAPODS_VERSION_MAJOR_PromiseKit_Until 1
#define COCOAPODS_VERSION_MINOR_PromiseKit_Until 5
#define COCOAPODS_VERSION_PATCH_PromiseKit_Until 3

// PromiseKit/When
#define COCOAPODS_POD_AVAILABLE_PromiseKit_When
#define COCOAPODS_VERSION_MAJOR_PromiseKit_When 1
#define COCOAPODS_VERSION_MINOR_PromiseKit_When 5
#define COCOAPODS_VERSION_PATCH_PromiseKit_When 3

// Debug_Staging build configuration
#ifdef DEBUG_STAGING

  // Aperitif
  #define COCOAPODS_POD_AVAILABLE_Aperitif
  #define COCOAPODS_VERSION_MAJOR_Aperitif 0
  #define COCOAPODS_VERSION_MINOR_Aperitif 1
  #define COCOAPODS_VERSION_PATCH_Aperitif 0

  // Reveal-iOS-SDK
  #define COCOAPODS_POD_AVAILABLE_Reveal_iOS_SDK
  #define COCOAPODS_VERSION_MAJOR_Reveal_iOS_SDK 1
  #define COCOAPODS_VERSION_MINOR_Reveal_iOS_SDK 5
  #define COCOAPODS_VERSION_PATCH_Reveal_iOS_SDK 1

#endif
// Debug_Production build configuration
#ifdef DEBUG_PRODUCTION

  // Aperitif
  #define COCOAPODS_POD_AVAILABLE_Aperitif
  #define COCOAPODS_VERSION_MAJOR_Aperitif 0
  #define COCOAPODS_VERSION_MINOR_Aperitif 1
  #define COCOAPODS_VERSION_PATCH_Aperitif 0

  // Reveal-iOS-SDK
  #define COCOAPODS_POD_AVAILABLE_Reveal_iOS_SDK
  #define COCOAPODS_VERSION_MAJOR_Reveal_iOS_SDK 1
  #define COCOAPODS_VERSION_MINOR_Reveal_iOS_SDK 5
  #define COCOAPODS_VERSION_PATCH_Reveal_iOS_SDK 1

#endif
// AdHoc_Staging build configuration
#ifdef ADHOC_STAGING

  // Aperitif
  #define COCOAPODS_POD_AVAILABLE_Aperitif
  #define COCOAPODS_VERSION_MAJOR_Aperitif 0
  #define COCOAPODS_VERSION_MINOR_Aperitif 1
  #define COCOAPODS_VERSION_PATCH_Aperitif 0

#endif
// AdHoc_Production build configuration
#ifdef ADHOC_PRODUCTION

  // Aperitif
  #define COCOAPODS_POD_AVAILABLE_Aperitif
  #define COCOAPODS_VERSION_MAJOR_Aperitif 0
  #define COCOAPODS_VERSION_MINOR_Aperitif 1
  #define COCOAPODS_VERSION_PATCH_Aperitif 0

#endif
